using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ArchipelagoRandomizer;

public enum Location
{
    // Default Locations
    SPACESHIP, // no longer in use; keeping for backwards compatibility with existing mod save files
    SS,
    ET_DRUM,
    ET_HEL,
    ET_SC_SHRINE,
    ET_QML,
    ET_FOSSIL,
    ET_LAKEBED_CAVE,
    ET_COLEUS_CAVE,
    ET_SHARD_SIGNAL,
    ET_EP2_SIGNAL,
    ET_SC,
    ET_QML_TR,
    ET_QML_TANK,
    ET_CHERT_TANK,
    AT_HGT_TOWERS,
    AT_BH_TOWER,
    AT_ATP,
    TH_GM,
    TH_ZERO_G,
    TH_HAL,
    TH_HORNFELS,
    TH_SEED_CRATER,
    TH_MINES,
    TH_MS_SIGNAL,
    TH_GS_SIGNAL,
    TH_GALENA_SIGNAL,
    TH_TEPHRA_SIGNAL,
    TH_CAMPFIRE_NOTE,
    TH_GROVE_PLAQUE,
    AR_WHISTLE,
    AR_ESL,
    AR_ESL_TR,
    AR_ICE_TR,
    AR_ICE_TANK,
    AR_LL,
    AR_ESKER_TANK,
    BH_BANJO,
    BH_OBSERVATORY,
    BH_OS_MURAL,
    BH_FORGE,
    BH_TOWER,
    BH_SHARD_SIGNAL,
    BH_EP1_SIGNAL,
    BH_NG_NOTE,
    BH_OBSERVATORY_TR,
    BH_CAMPSITE_NOTE,
    BH_SOLANUM_REPORT,
    BH_HC_SHRINE,
    BH_HC,
    BH_NG_TANK,
    BH_RIEBECK_TANK,
    HL_VTS,
    WHS,
    OPC_ENTER,
    OPC_CM,
    GD_FLUTE,
    GD_BI,
    GD_CY,
    GD_SIW,
    GD_DEPTHS,
    GD_CORE,
    GD_TOWER_RULE,
    GD_TOWER_COMPLETE,
    GD_COORDINATES,
    GD_SHARD_SIGNAL,
    GD_STATUE,
    GD_SHIP,
    GD_BI_TANK,
    GD_GABBRO_TANK,
    FROZEN_SHUTTLE,
    IL_CORE,
    SOLANUM_SHUTTLE,
    QM_LAND,
    QM_6L,
    QM_SIGNAL,
    DB_HARMONICA,
    DB_JELLY,
    DB_JELLY_TR,
    DB_GRAVE,
    DB_VESSEL,
    DB_EP3_SIGNAL,
    DB_FELDSPAR_TANK,
    FREQ_DISTRESS,
    FREQ_QUANTUM,
    FREQ_HIDE_SEEK,

    // didn't add these until DLC integration because I was unsure if a DLC-less game had these
    DSR_TOWER_SIGNAL,
    DSR_SATELLITE_SIGNAL,
    SATELLITE_TR,

    // DLC Locations
    RL_WORKSHOP,
    RL_SR,
    CI_EYE,
    CI_SR,
    CI_TOWER_SR,
    HG_SR,
    HG_LAB_SR,
    RESERVOIR_CRAFT_PROJECTION,
    RESERVOIR_STRANGER_PROJECTION,
    RESERVOIR_SR,
    SUBMERGED_STRUCTURE,
    ARTIFACT,
    SW_BRIDGE,
    SC_BURNED,
    SC_TOWER_UPPER,
    EC_MURAL,
    VAULT_VISION,
    SL_GREEN_LIGHT,
    CI_SYMBOL_ROOM,
    TEMPLE_ENTER,
    TEMPLE_SR,
    TEMPLE_MAPS,
    RL_SECRET_SR,
    CI_SECRET_SR,
    HG_SECRET_SR,
    SW_FA_STORY_SR,
    SW_FA_GLITCH_SR,
    SC_FA_STORY_SR,
    SC_FA_GLITCH_SR_1,
    SC_FA_GLITCH_SR_2,
    EC_FA_STORY_SR,
    EC_FA_GLITCH_SR,
    SL_VAULT,

    // Logsanity Locations (SLF = Ship Log Fact)
    SLF__S_SUNSTATION_X1,
    SLF__S_SUNSTATION_X2,
    SLF__S_SUNSTATION_X3,
    SLF__S_SUNSTATION_X4,
    SLF__CT_CHERT_X1,
    SLF__CT_CHERT_X2,
    SLF__CT_CHERT_X3,
    SLF__CT_CHERT_X4,
    SLF__CT_CHERT_X5,
    SLF__CT_QUANTUM_MOON_LOCATOR_X1,
    SLF__CT_QUANTUM_MOON_LOCATOR_X2,
    SLF__CT_QUANTUM_MOON_LOCATOR_X3,
    SLF__CT_GRAVITY_CANNON_X1,
    SLF__CT_GRAVITY_CANNON_X2,
    SLF__CT_ESCAPE_POD_X1,
    SLF__CT_ESCAPE_POD_X2,
    SLF__CT_HIGH_ENERGY_LAB_X1,
    SLF__CT_HIGH_ENERGY_LAB_X2,
    SLF__CT_HIGH_ENERGY_LAB_X3,
    SLF__CT_WARP_TOWER_MAP_X1,
    SLF__CT_WARP_TOWER_MAP_X4,
    SLF__CT_WARP_TOWER_MAP_X3,
    SLF__CT_WARP_TOWER_MAP_X2,
    SLF__CT_SUNLESS_CITY_X1,
    SLF__CT_SUNLESS_CITY_X2,
    SLF__CT_SUNLESS_CITY_X3,
    SLF__CT_ANGLERFISH_FOSSIL_X1,
    SLF__CT_ANGLERFISH_FOSSIL_X2,
    SLF__CT_ANGLERFISH_FOSSIL_X3,
    SLF__CT_QUANTUM_CAVES_X1,
    SLF__CT_QUANTUM_CAVES_X2,
    SLF__CT_LAKEBED_CAVERN_X1,
    SLF__CT_LAKEBED_CAVERN_X2,
    SLF__CT_LAKEBED_CAVERN_X3,
    SLF__TT_WARP_TOWERS_X1,
    SLF__TT_WARP_TOWERS_X2,
    SLF__TT_TIME_LOOP_DEVICE_X1,
    SLF__TT_TIME_LOOP_DEVICE_X2,
    SLF__TT_TIME_LOOP_DEVICE_X3,
    SLF__TT_TIME_LOOP_DEVICE_X4,
    SLF__TT_TIME_LOOP_DEVICE_X5,
    SLF__TH_VILLAGE_X1,
    SLF__TH_VILLAGE_X2,
    // Logsanity no longer generates the Village 3 location because it turns out this fact is perma-missable.
    // Keeping it here for backwards compatibility and to document that this is intentional.
    SLF__TH_VILLAGE_X3,
    SLF__TH_ZERO_G_CAVE_X1,
    SLF__TH_ZERO_G_CAVE_X2,
    SLF__TH_IMPACT_CRATER_X1,
    SLF__TH_IMPACT_CRATER_X2,
    SLF__TH_IMPACT_CRATER_X3,
    SLF__TH_NOMAI_MINE_X1,
    SLF__TH_NOMAI_MINE_X2,
    SLF__TH_NOMAI_MINE_X3,
    SLF__TH_QUANTUM_SHARD_X1,
    SLF__TH_QUANTUM_SHARD_X2,
    SLF__TM_ESKER_X1,
    SLF__TM_NORTH_POLE_X1,
    SLF__TM_EYE_LOCATOR_X1,
    SLF__TM_EYE_LOCATOR_X2,
    SLF__BH_RIEBECK_X1,
    SLF__BH_RIEBECK_X2,
    SLF__BH_GRAVITY_CANNON_X1,
    SLF__BH_GRAVITY_CANNON_X2,
    SLF__BH_QUANTUM_RESEARCH_TOWER_X1,
    SLF__BH_QUANTUM_RESEARCH_TOWER_X2,
    SLF__BH_QUANTUM_RESEARCH_TOWER_X3,
    SLF__BH_QUANTUM_SHARD_X1,
    SLF__BH_QUANTUM_SHARD_X2,
    SLF__BH_QUANTUM_SHARD_X3,
    SLF__BH_WARP_RECEIVER_X1,
    SLF__BH_WARP_RECEIVER_X2,
    SLF__BH_ESCAPE_POD_X1,
    SLF__BH_ESCAPE_POD_X2,
    SLF__BH_OLD_SETTLEMENT_X1,
    SLF__BH_OLD_SETTLEMENT_X2,
    SLF__BH_OLD_SETTLEMENT_X3,
    SLF__BH_OLD_SETTLEMENT_X4,
    SLF__BH_MURAL_3_X1,
    SLF__BH_MURAL_2_X1,
    SLF__BH_MURAL_1_X1,
    SLF__BH_HANGING_CITY_X1,
    SLF__BH_HANGING_CITY_X2,
    SLF__BH_HANGING_CITY_X3,
    SLF__BH_HANGING_CITY_X4,
    // there are 5 BHF facts, but the game's fact ids skip over 2 for some reason
    SLF__BH_BLACK_HOLE_FORGE_X1,
    SLF__BH_BLACK_HOLE_FORGE_X3,
    SLF__BH_BLACK_HOLE_FORGE_X4,
    SLF__BH_BLACK_HOLE_FORGE_X5,
    SLF__BH_BLACK_HOLE_FORGE_X6,
    SLF__BH_WARP_ALIGNMENT_MAP_X1,
    SLF__BH_WARP_ALIGNMENT_MAP_X2,
    SLF__BH_WARP_ALIGNMENT_MAP_X3,
    SLF__BH_WARP_ALIGNMENT_MAP_X4,
    SLF__BH_OBSERVATORY_X1,
    SLF__BH_OBSERVATORY_X2,
    SLF__BH_OBSERVATORY_X3,
    SLF__BH_OBSERVATORY_X4,
    SLF__BH_TORNADO_SIMULATION_X1,
    SLF__BH_TORNADO_SIMULATION_X2,
    SLF__VM_VOLCANO_X1,
    SLF__VM_VOLCANO_X2,
    SLF__VM_VOLCANO_X3,
    SLF__GD_OCEAN_X1,
    SLF__GD_OCEAN_X2,
    SLF__GD_GABBRO_ISLAND_X0,
    SLF__GD_GABBRO_ISLAND_X1,
    SLF__GD_GABBRO_ISLAND_X2,
    SLF__GD_GABBRO_ISLAND_X3,
    SLF__GD_CONSTRUCTION_YARD_X1,
    SLF__GD_CONSTRUCTION_YARD_X2,
    SLF__GD_CONSTRUCTION_YARD_X3,
    SLF__GD_BRAMBLE_ISLAND_X1,
    SLF__GD_STATUE_ISLAND_X1,
    SLF__GD_STATUE_ISLAND_X2,
    SLF__GD_STATUE_WORKSHOP_X1,
    SLF__GD_STATUE_WORKSHOP_X2,
    SLF__GD_STATUE_WORKSHOP_X3,
    SLF__GD_QUANTUM_TOWER_X1,
    SLF__GD_QUANTUM_TOWER_X2,
    SLF__GD_QUANTUM_TOWER_X3,
    SLF__GD_QUANTUM_TOWER_X4,
    SLF__ORBITAL_PROBE_CANNON_X1,
    SLF__ORBITAL_PROBE_CANNON_X2,
    SLF__ORBITAL_PROBE_CANNON_X3,
    SLF__OPC_SUNKEN_MODULE_X1,
    SLF__OPC_SUNKEN_MODULE_X2,
    SLF__OPC_SUNKEN_MODULE_X3,
    SLF__OPC_EYE_COORDINATES_X1,
    SLF__OPC_BROKEN_MODULE_X1,
    SLF__OPC_BROKEN_MODULE_X2,
    SLF__OPC_BROKEN_MODULE_X3,
    SLF__OPC_INTACT_MODULE_X1,
    SLF__OPC_INTACT_MODULE_X2,
    SLF__DB_FELDSPAR_X1,
    SLF__DB_FELDSPAR_X2,
    SLF__DB_FELDSPAR_X3,
    SLF__DB_FROZEN_JELLYFISH_X1,
    SLF__DB_FROZEN_JELLYFISH_X2,
    SLF__DB_FROZEN_JELLYFISH_X3,
    SLF__DB_ESCAPE_POD_X1,
    SLF__DB_ESCAPE_POD_X2,
    SLF__DB_ESCAPE_POD_X3,
    SLF__DB_NOMAI_GRAVE_X1,
    SLF__DB_NOMAI_GRAVE_X2,
    SLF__DB_NOMAI_GRAVE_X3,
    SLF__DB_NOMAI_GRAVE_X4,
    SLF__DB_VESSEL_X1,
    SLF__DB_VESSEL_X2,
    SLF__DB_VESSEL_X3,
    SLF__DB_VESSEL_X4,
    SLF__DB_VESSEL_X5,
    SLF__DB_VESSEL_X6,
    SLF__WHS_X1,
    SLF__WHS_X2,
    SLF__WHS_X3,
    SLF__WHS_X4,
    SLF__COMET_SHUTTLE_X1,
    SLF__COMET_SHUTTLE_X2,
    SLF__COMET_SHUTTLE_X3,
    SLF__COMET_SHUTTLE_X4,
    SLF__COMET_INTERIOR_X1,
    SLF__COMET_INTERIOR_X2,
    SLF__COMET_INTERIOR_X3,
    SLF__COMET_INTERIOR_X4,
    SLF__QUANTUM_MOON_X1,
    SLF__QUANTUM_MOON_X2,
    SLF__QM_SHUTTLE_X1,
    SLF__QM_SHUTTLE_X2,
    SLF__QM_SHRINE_X1,
    SLF__QM_SHRINE_X2,
    SLF__QM_SHRINE_X3,
    SLF__QM_SHRINE_X4,
    SLF__QM_SIXTH_LOCATION_X1,
    SLF__QM_SIXTH_LOCATION_X3,
    SLF__QM_SIXTH_LOCATION_X5,
    SLF__QM_SIXTH_LOCATION_X4,
    SLF__QM_SIXTH_LOCATION_X2,
    SLF__QM_SIXTH_LOCATION_X6,

    SLF__TH_RADIO_TOWER_X1,

    // DLC & Logsanity Locations
    SLF__IP_RING_WORLD_X1,
    SLF__IP_ZONE_1_X1,
    SLF__IP_ZONE_1_X2,
    SLF__IP_ZONE_1_STORY_X1,
    SLF__IP_ZONE_1_STORY_X2,
    SLF__IP_ZONE_1_SECRET_X2,
    SLF__IP_ZONE_1_SECRET_X1,
    SLF__IP_ZONE_2_X1,
    SLF__IP_ZONE_2_X2,
    SLF__IP_ZONE_2_STORY_X1,
    SLF__IP_ZONE_2_STORY_X2,
    SLF__IP_ZONE_2_SECRET_X2,
    SLF__IP_ZONE_2_SECRET_X1,
    SLF__IP_ZONE_2_LIGHTHOUSE_X2,
    SLF__IP_ZONE_2_LIGHTHOUSE_X1,
    SLF__IP_ZONE_2_CODE_X1,
    SLF__IP_ZONE_2_CODE_X2,
    SLF__IP_ZONE_2_CODE_X3,
    SLF__IP_ZONE_3_X1,
    SLF__IP_ZONE_3_SECRET_X2,
    SLF__IP_ZONE_3_SECRET_X1,
    SLF__IP_ZONE_3_STORY_X1,
    SLF__IP_ZONE_3_STORY_X2,
    SLF__IP_ZONE_3_ENTRANCE_X1,
    SLF__IP_ZONE_3_ENTRANCE_X2,
    SLF__IP_ZONE_3_ENTRANCE_X3,
    SLF__IP_ZONE_3_LAB_X1,
    SLF__IP_ZONE_3_LAB_X3,
    SLF__IP_ZONE_3_LAB_X4,
    SLF__IP_ZONE_3_LAB_X2,
    SLF__IP_MAP_PROJECTION_1_X1,
    SLF__IP_MAP_PROJECTION_2_X1,
    SLF__IP_MAP_PROJECTION_3_X1,
    SLF__IP_ZONE_4_X2,
    SLF__IP_ZONE_4_X3,
    SLF__IP_ZONE_4_X4,
    SLF__IP_ZONE_4_STORY_X1,
    SLF__IP_ZONE_4_STORY_X2,
    SLF__IP_PRISON_X1,
    SLF__IP_PRISON_X2,
    SLF__IP_DREAM_LAKE_X1,
    SLF__IP_DREAM_LAKE_X2,
    SLF__IP_SARCOPHAGUS_X2,
    SLF__IP_SARCOPHAGUS_X3,
    SLF__IP_SARCOPHAGUS_X4,
    SLF__IP_SARCOPHAGUS_X5,
    SLF__IP_DREAM_ZONE_1_X1,
    SLF__IP_DREAM_ZONE_1_X2,
    SLF__IP_DREAM_ZONE_1_X3,
    SLF__IP_DREAM_LIBRARY_1_X1,
    SLF__IP_DREAM_LIBRARY_1_X2,
    SLF__IP_DREAM_1_STORY_X1,
    SLF__IP_DREAM_1_STORY_X2,
    SLF__IP_DREAM_1_RULE_X1,
    SLF__IP_DREAM_ZONE_2_X1,
    SLF__IP_DREAM_ZONE_2_X2,
    SLF__IP_DREAM_ZONE_2_X3,
    SLF__IP_DREAM_ZONE_2_X4,
    SLF__IP_DREAM_LIBRARY_2_X1,
    SLF__IP_DREAM_LIBRARY_2_X2,
    SLF__IP_DREAM_2_STORY_X1,
    SLF__IP_DREAM_2_STORY_X2,
    SLF__IP_DREAM_2_RULE_X1,
    SLF__IP_DREAM_2_RULE_X2,
    SLF__IP_DREAM_ZONE_3_X1,
    SLF__IP_DREAM_ZONE_3_X2,
    SLF__IP_DREAM_LIBRARY_3_X1,
    SLF__IP_DREAM_LIBRARY_3_X2,
    SLF__IP_DREAM_3_STORY_X1,
    SLF__IP_DREAM_3_STORY_X2,
    SLF__IP_DREAM_3_RULE_X1,

    /* Rumorsanity Locations
    SLF__S_SUNSTATION_R1,
    SLF__S_SUNSTATION_R2,
    SLF__S_SUNSTATION_R3,
    SLF__CT_GRAVITY_CANNON_R1,
    SLF__CT_ESCAPE_POD_R1,
    SLF__CT_ESCAPE_POD_R2,
    SLF__CT_HIGH_ENERGY_LAB_R1,
    SLF__CT_HIGH_ENERGY_LAB_R2,
    SLF__CT_HIGH_ENERGY_LAB_R3,
    SLF__CT_WARP_TOWER_MAP_R1,
    SLF__CT_SUNLESS_CITY_R1,
    SLF__CT_SUNLESS_CITY_R3,
    SLF__CT_SUNLESS_CITY_R4,
    SLF__CT_SUNLESS_CITY_R5,
    SLF__CT_SUNLESS_CITY_R2,
    SLF__CT_ANGLERFISH_FOSSIL_R1,
    SLF__CT_ANGLERFISH_FOSSIL_R2,
    SLF__CT_ANGLERFISH_FOSSIL_R3,
    SLF__CT_ANGLERFISH_FOSSIL_R4,
    SLF__CT_QUANTUM_CAVES_R1,
    SLF__CT_LAKEBED_CAVERN_R1,
    SLF__CT_LAKEBED_CAVERN_R2,
    SLF__TT_TIME_LOOP_DEVICE_R1,
    SLF__TT_TIME_LOOP_DEVICE_R2,
    SLF__TT_TIME_LOOP_DEVICE_R3,
    SLF__TT_TIME_LOOP_DEVICE_R4,
    SLF__TH_ZERO_G_CAVE_R1,
    SLF__TH_IMPACT_CRATER_R1,
    SLF__TH_NOMAI_MINE_R1,
    SLF__TH_QUANTUM_SHARD_R1,
    SLF__TH_QUANTUM_SHARD_R2,
    SLF__TM_ESKER_R1,
    SLF__TM_NORTH_POLE_R1,
    SLF__TM_EYE_LOCATOR_R1,
    SLF__TM_EYE_LOCATOR_R2,
    SLF__BH_RIEBECK_R1,
    SLF__BH_RIEBECK_R2,
    SLF__BH_RIEBECK_R3,
    SLF__BH_RIEBECK_R4,
    SLF__BH_QUANTUM_RESEARCH_TOWER_R1,
    SLF__BH_QUANTUM_RESEARCH_TOWER_R2,
    SLF__BH_QUANTUM_SHARD_R1,
    SLF__BH_ESCAPE_POD_R1,
    SLF__BH_OLD_SETTLEMENT_R1,
    SLF__BH_HANGING_CITY_R1,
    SLF__BH_HANGING_CITY_R2,
    SLF__BH_BLACK_HOLE_FORGE_R1,
    SLF__BH_BLACK_HOLE_FORGE_R2,
    SLF__BH_BLACK_HOLE_FORGE_R3,
    SLF__BH_BLACK_HOLE_FORGE_R4,
    SLF__BH_OBSERVATORY_R1,
    SLF__BH_OBSERVATORY_R2,
    SLF__BH_OBSERVATORY_R3,
    SLF__BH_OBSERVATORY_R4,
    SLF__BH_TORNADO_SIMULATION_R1,
    SLF__GD_OCEAN_R1,
    SLF__GD_OCEAN_R2,
    SLF__GD_OCEAN_R3,
    SLF__GD_GABBRO_ISLAND_R1,
    SLF__GD_CONSTRUCTION_YARD_R1,
    SLF__GD_STATUE_ISLAND_R1,
    SLF__GD_STATUE_ISLAND_R2,
    SLF__GD_STATUE_WORKSHOP_R1,
    SLF__GD_STATUE_WORKSHOP_R2,
    SLF__GD_STATUE_WORKSHOP_R3,
    SLF__GD_QUANTUM_TOWER_R1,
    SLF__ORBITAL_PROBE_CANNON_R1,
    SLF__ORBITAL_PROBE_CANNON_R2,
    SLF__ORBITAL_PROBE_CANNON_R4,
    SLF__ORBITAL_PROBE_CANNON_R3,
    SLF__OPC_SUNKEN_MODULE_R1,
    SLF__OPC_SUNKEN_MODULE_R5,
    SLF__OPC_SUNKEN_MODULE_R4,
    SLF__OPC_SUNKEN_MODULE_R2,
    SLF__OPC_SUNKEN_MODULE_R3,
    SLF__OPC_BROKEN_MODULE_R1,
    SLF__OPC_BROKEN_MODULE_R2,
    SLF__OPC_BROKEN_MODULE_R3,
    SLF__OPC_INTACT_MODULE_R1,
    SLF__DB_FELDSPAR_R1,
    SLF__DB_FELDSPAR_R2,
    SLF__DB_FROZEN_JELLYFISH_R1,
    SLF__DB_ESCAPE_POD_R1,
    SLF__DB_NOMAI_GRAVE_R1,
    SLF__DB_NOMAI_GRAVE_R2,
    SLF__DB_VESSEL_R1,
    SLF__DB_VESSEL_R2,
    SLF__DB_VESSEL_R3,
    SLF__DB_VESSEL_R4,
    SLF__WHS_R1,
    SLF__WHS_R2,
    SLF__WHS_R3,
    SLF__WHS_R4,
    SLF__COMET_INTERIOR_R1,
    SLF__COMET_INTERIOR_R2,
    SLF__QUANTUM_MOON_R1,
    SLF__QUANTUM_MOON_R2,
    SLF__QUANTUM_MOON_R3,
    SLF__QUANTUM_MOON_R4,
    SLF__QM_SHRINE_R1,
    SLF__QM_SIXTH_LOCATION_R1,
    SLF__QM_SIXTH_LOCATION_R2,
    SLF__QM_SIXTH_LOCATION_R3,
     */

    /* DLC & Rumorsanity Locations
    SLF__IP_ZONE_1_SECRET_R1,
    SLF__IP_ZONE_2_SECRET_R1,
    SLF__IP_ZONE_2_LIGHTHOUSE_R1,
    SLF__IP_ZONE_2_CODE_R1,
    SLF__IP_ZONE_2_CODE_R2,
    SLF__IP_ZONE_3_SECRET_R1,
    SLF__IP_ZONE_3_ENTRANCE_R1,
    SLF__IP_ZONE_3_LAB_R1,
    SLF__IP_PRISON_R1,
    SLF__IP_PRISON_R2,
    SLF__IP_DREAM_LAKE_R1,
    SLF__IP_DREAM_LAKE_R2,
    SLF__IP_SARCOPHAGUS_R4,
    SLF__IP_SARCOPHAGUS_R1,
    SLF__IP_SARCOPHAGUS_R2,
    SLF__IP_SARCOPHAGUS_R3,
    SLF__IP_DREAM_ZONE_1_R1,
    SLF__IP_DREAM_LIBRARY_1_R1,
    SLF__IP_DREAM_ZONE_2_R1,
    SLF__IP_DREAM_LIBRARY_2_R1,
    SLF__IP_DREAM_ZONE_3_R1,
    SLF__IP_DREAM_LIBRARY_3_R1,
     */
};

public static class LocationNames
{
    public static bool IsDefaultLocation(Location location) =>
        location >= Location.SS && location <= Location.SATELLITE_TR;
    public static bool IsDLCDefaultLocation(Location location) =>
        location >= Location.RL_WORKSHOP && location <= Location.SL_VAULT;
    public static bool IsLogsanityLocation(Location location) =>
        location >= Location.SLF__S_SUNSTATION_X1 && location <= Location.SLF__QM_SIXTH_LOCATION_X6;
    public static bool IsDLCLogsanityLocation(Location location) =>
        location >= Location.SLF__TH_RADIO_TOWER_X1 && location <= Location.SLF__IP_DREAM_3_RULE_X1;

    // When story mods are added, these methods will have to consider those options too
    public static bool IsLocationActive(Location loc)
    {
        if (loc == Location.SLF__TH_VILLAGE_X3) return false;

        bool logsanityIsOn = APRandomizer.SlotEnabledLogsanity();
        bool dlcIsOn = APRandomizer.SlotEnabledEotEDLC();

        if (IsLogsanityLocation(loc) && !logsanityIsOn) return false;
        if (IsDLCDefaultLocation(loc) && !dlcIsOn) return false;
        if (IsDLCLogsanityLocation(loc) && (!logsanityIsOn || !dlcIsOn)) return false;

        return true;
    }
    public static IEnumerable<Location> ActiveLocations() => locationNames.Keys.Where(loc => IsLocationActive(loc));

    public static Dictionary<Location, string> locationNames = new Dictionary<Location, string> {
        { Location.SS, "Sun Station (Projection Stone Text)" },

        { Location.ET_HEL, "ET: High Energy Lab (Upper Text Wall)" },
        { Location.ET_SC_SHRINE, "ET: Sunless City Shrine (Entrance Text Wall)" },
        { Location.ET_QML, "ET: QM Locator (2nd Scroll)" },
        { Location.ET_FOSSIL, "ET: Fossil (Children's Text)" },
        { Location.ET_LAKEBED_CAVE, "ET: Lakebed Cave (Floor Text)" },
        { Location.ET_COLEUS_CAVE, "ET: Coleus' Cave (Text Wall)" },
        { Location.ET_SC, "ET: Enter Sunless City" },
        { Location.ET_QML_TR, "ET: Chert's QM Locator Recorder" },
        { Location.ET_QML_TANK, "ET: QM Locator Fuel Tank" },
        { Location.ET_CHERT_TANK, "ET: Chert's Camp Fuel Tank" },

        { Location.AT_ATP, "AT: Enter the ATP" },
        { Location.AT_HGT_TOWERS, "AT: HGT Towers (Text Wall)" },
        { Location.AT_BH_TOWER, "AT: BH Tower (Text Wall)" },

        { Location.TH_GM, "TH: Ghost Matter Plaque" },
        { Location.TH_ZERO_G, "TH: Zero-G Repairs" },
        { Location.TH_HAL, "TH: Get the Translator from Hal" },
        { Location.TH_HORNFELS, "TH: Talk to Hornfels" },
        { Location.TH_SEED_CRATER, "TH: Talk to Tektite about Bramble Seed" },
        { Location.TH_MINES, "TH: Mines (Text Wall)" },
        { Location.TH_CAMPFIRE_NOTE, "TH: Hornfels' Radio Tower Campfire Note" },
        { Location.TH_GROVE_PLAQUE, "TH: Chert's Grove Shard Plaque" },

        { Location.AR_ESL, "AR: Signal Locator (Text Wall)" },
        { Location.AR_ESL_TR, "AR: Riebeck's Signal Locator Recorder" },
        { Location.AR_ICE_TR, "AR: Chert's Ice Crater Recorder" },
        { Location.AR_ICE_TANK, "AR: Ice Crater Fuel Tank" },
        { Location.AR_LL, "AR: Esker's Lunar Lookout Plaque" },
        { Location.AR_ESKER_TANK, "AR: Esker's House Fuel Tank" },

        { Location.BH_OBSERVATORY, "BH: Southern Observatory (Tornado Text Wall)" },
        { Location.BH_OS_MURAL, "BH: Old Settlement Murals" },
        { Location.BH_FORGE, "BH: Forge (2nd Scroll)" },
        { Location.BH_TOWER, "BH: Tower (Top Floor Text Wall)" },
        { Location.BH_NG_NOTE, "BH: Feldspar's Spare Fuel Note" },
        { Location.BH_OBSERVATORY_TR, "BH: Riebeck's Southern Observatory Recorder" },
        { Location.BH_CAMPSITE_NOTE, "BH: Riebeck's Surface Campsite Note" },
        { Location.BH_SOLANUM_REPORT, "BH: Solanum's Class Report (2nd Scroll)" },
        { Location.BH_HC_SHRINE, "BH: Hanging City Shrine (Text Wall)" },
        { Location.BH_HC, "BH: Visit Hanging City" },
        { Location.BH_NG_TANK, "BH: Northern Glacier Fuel Tank" },
        { Location.BH_RIEBECK_TANK, "BH: Riebeck's Camp Fuel Tank" },

        { Location.HL_VTS, "HL: Volcanic Testing Site (Text Wall)" },

        { Location.WHS, "WHS (Text Wall)" },

        { Location.OPC_ENTER, "GD: Enter the Orbital Probe Cannon" },
        { Location.OPC_CM, "GD: Control Module Logs (Text Wheels)" },
        { Location.GD_BI, "GD: Bramble Island Recorder" },
        { Location.GD_CY, "GD: Construction Yard (Text Wall)" },
        { Location.GD_SIW, "GD: Statue Island Workshop (Text Wheel)" },
        { Location.GD_DEPTHS, "GD: Enter the Ocean Depths" },
        { Location.GD_CORE, "GD: Enter the Core" },
        { Location.GD_TOWER_RULE, "GD: Tower Rule (Pedestal Text)" },
        { Location.GD_TOWER_COMPLETE, "GD: Complete the Tower (Text Wall)" },
        { Location.GD_COORDINATES, "GD: See the Coordinates" }, // spoiler-free name, as opposed to e.g. "Eye of the Universe Coordinates"
        { Location.GD_STATUE, "GD: Find Gabbro's Statue" },
        { Location.GD_SHIP, "GD: Find Gabbro's Ship" },
        { Location.GD_BI_TANK, "GD: Bramble Island Fuel Tank" },
        { Location.GD_GABBRO_TANK, "GD: Gabbro's Camp Fuel Tank" },

        { Location.FROZEN_SHUTTLE, "Frozen Shuttle Log (Text Wheel)" },
        { Location.IL_CORE, "Ruptured Core (Text Wheel)" }, // spoiler-free name, as opposed to e.g. "Interloper Core"

        { Location.QM_LAND, "QM: Land" },
        { Location.SOLANUM_SHUTTLE, "Solanum's Shuttle Log (Text Wheel)" },
        { Location.QM_6L, "QM: Explore the Sixth Location" }, // spoiler-free name, as opposed to e.g. "Meet Solanum"

        { Location.DB_JELLY, "DB: Feldspar's Note" }, // spoiler-free name, as opposed to e.g. "Frozen Jellyfish Note"
        { Location.DB_JELLY_TR, "DB: Feldspar's Recorder" }, // spoiler-free name, as opposed to e.g. "Frozen Jellyfish Recorder"
        { Location.DB_GRAVE, "DB: Nomai Grave (Text Wheel)" },
        { Location.DB_VESSEL, "DB: Find The Vessel" },
        { Location.DB_FELDSPAR_TANK, "DB: Feldspar's Camp Fuel Tank" },

        { Location.FREQ_DISTRESS, "Scan Any Distress Beacon" },
        { Location.FREQ_QUANTUM, "Scan Any Quantum Fluctuation" },
        { Location.FREQ_HIDE_SEEK, "TH: Receive Hide & Seek Frequency" },

        { Location.ET_DRUM, "ET: Scan Drum Signal" },
        { Location.AR_WHISTLE, "AR: Scan Whistling Signal" },
        { Location.BH_BANJO, "BH: Scan Banjo Signal" },
        { Location.GD_FLUTE, "GD: Scan Flute Signal" },
        { Location.DB_HARMONICA, "DB: Scan Harmonica Signal" },
        { Location.TH_MS_SIGNAL, "TH: Scan Museum Shard Signal" },
        { Location.TH_GS_SIGNAL, "TH: Scan Grove Shard Signal" },
        { Location.ET_SHARD_SIGNAL, "ET: Scan Cave Shard Signal" },
        { Location.BH_SHARD_SIGNAL, "BH: Scan Tower Shard Signal" },
        { Location.GD_SHARD_SIGNAL, "GD: Scan Island Shard Signal" },
        { Location.QM_SIGNAL, "Scan QM Signal" },
        { Location.BH_EP1_SIGNAL, "BH: Scan Escape Pod 1 Signal" },
        { Location.ET_EP2_SIGNAL, "ET: Scan Escape Pod 2 Signal" },
        { Location.DB_EP3_SIGNAL, "DB: Scan Escape Pod 3 Signal" },
        { Location.TH_GALENA_SIGNAL, "TH: Scan Galena's Radio Signal" },
        { Location.TH_TEPHRA_SIGNAL, "TH: Scan Tephra's Radio Signal" },

        // didn't add these until DLC integration because I was unsure if a DLC-less game had these
        { Location.DSR_TOWER_SIGNAL, "TH: Scan Radio Tower Signal" },
        { Location.DSR_SATELLITE_SIGNAL, "Scan Deep Space Satellite Signal" },
        { Location.SATELLITE_TR, "Gabbro's Satellite Recorder" },

        // DLC Locations
        { Location.RL_WORKSHOP, "EotE: River Lowlands Workshop" },
        { Location.RL_SR, "EotE: River Lowlands Slide Reel" },
        { Location.CI_EYE, "EotE: Cinder Isles Eye" },
        { Location.CI_SR, "EotE: Cinder Isles Slide Reel" },
        { Location.CI_TOWER_SR, "EotE: Island Tower Slide Reel" },
        { Location.HG_SR, "EotE: Hidden Gorge Slide Reel" },
        { Location.HG_LAB_SR, "EotE: Laboratory Experiments Slide Reel" },
        { Location.RESERVOIR_CRAFT_PROJECTION, "EotE: Reservoir Jammer Projection" },
        { Location.RESERVOIR_STRANGER_PROJECTION, "EotE: Reservoir Stranger Projection" },
        { Location.RESERVOIR_SR, "EotE: Reservoir Slide Reel" },
        { Location.SUBMERGED_STRUCTURE, "EotE: Submerged Structure" },
        { Location.ARTIFACT, "EotE: Find an Artifact" },

        { Location.SW_BRIDGE, "DW: Shrouded Woodlands Bridge" },
        { Location.SC_BURNED, "DW: Starlit Cove Burned Building" },
        { Location.SC_TOWER_UPPER, "DW: Starlit Cove Upper Tower Floors" },
        { Location.EC_MURAL, "DW: Endless Canyon Mural" },
        { Location.VAULT_VISION, "DW: Vault Vision" },
        { Location.SL_GREEN_LIGHT, "DW: Subterranean Lake Green Light" },

        { Location.CI_SYMBOL_ROOM, "EotE: Symbol Room Temple Code" },
        { Location.TEMPLE_ENTER, "EotE: Abandoned Temple" },
        { Location.TEMPLE_SR, "EotE: Abandoned Temple Slide Reel" },
        { Location.TEMPLE_MAPS, "EotE: Map Projections" },
        { Location.RL_SECRET_SR, "EotE: River Lowlands Secret Slide Reel" },
        { Location.CI_SECRET_SR, "EotE: Cinder Isles Secret Slide Reel" },
        { Location.HG_SECRET_SR, "EotE: Hidden Gorge Secret Slide Reel" },

        { Location.SW_FA_STORY_SR, "DW: Woodlands Archive Story Reel" },
        { Location.SW_FA_GLITCH_SR, "DW: Woodlands Archive Glitch Reel" },
        { Location.SC_FA_STORY_SR, "DW: Cove Archive Story Reel" },
        { Location.SC_FA_GLITCH_SR_1, "DW: Cove Archive 1st Glitch Reel" },
        { Location.SC_FA_GLITCH_SR_2, "DW: Cove Archive 2nd Glitch Reel" },
        { Location.EC_FA_STORY_SR, "DW: Canyon Archive Story Reel" },
        { Location.EC_FA_GLITCH_SR, "DW: Canyon Archive Glitch Reel" },
        { Location.SL_VAULT, "DW: Sealed Vault" },

        // Logsanity locations
        { Location.SLF__S_SUNSTATION_X1, "Ship Log: Sun Station 1 - Purpose" },
        { Location.SLF__S_SUNSTATION_X2, "Ship Log: Sun Station 2 - Test Result" },
        { Location.SLF__S_SUNSTATION_X3, "Ship Log: Sun Station 3 - Comet" },
        { Location.SLF__S_SUNSTATION_X4, "Ship Log: Sun Station 4 - Current Status" },
        { Location.SLF__CT_CHERT_X1, "ET Ship Log: Chert's Camp 1 - Visit" },
        { Location.SLF__CT_CHERT_X2, "ET Ship Log: Chert's Camp 2 - Supernovae" },
        { Location.SLF__CT_CHERT_X3, "ET Ship Log: Chert's Camp 3 - All The Stars" },
        { Location.SLF__CT_CHERT_X4, "ET Ship Log: Chert's Camp 4 - Old Age" },
        { Location.SLF__CT_CHERT_X5, "ET Ship Log: Chert's Camp 5 - Resignation" },
        { Location.SLF__CT_QUANTUM_MOON_LOCATOR_X1, "ET Ship Log: QM Locator 1 - Purpose" },
        { Location.SLF__CT_QUANTUM_MOON_LOCATOR_X2, "ET Ship Log: QM Locator 2 - Hypothesis" },
        { Location.SLF__CT_QUANTUM_MOON_LOCATOR_X3, "ET Ship Log: QM Locator 3 - Five Locations" },
        { Location.SLF__CT_GRAVITY_CANNON_X1, "ET Ship Log: Gravity Cannon 1 - Activate" },
        { Location.SLF__CT_GRAVITY_CANNON_X2, "ET Ship Log: Gravity Cannon 2 - Recall" },
        { Location.SLF__CT_ESCAPE_POD_X1, "ET Ship Log: Escape Pod 2 1 - Identify" },
        { Location.SLF__CT_ESCAPE_POD_X2, "ET Ship Log: Escape Pod 2 2 - Vessel" },
        { Location.SLF__CT_HIGH_ENERGY_LAB_X1, "ET Ship Log: High Energy Lab 1 - Temporal Anomaly" },
        { Location.SLF__CT_HIGH_ENERGY_LAB_X2, "ET Ship Log: High Energy Lab 2 - Increasing Interval" },
        { Location.SLF__CT_HIGH_ENERGY_LAB_X3, "ET Ship Log: High Energy Lab 3 - ATP" },
        // In the vanilla game, CT_WARP_TOWER_MAP_X2 is visually the 4th entry in the Tower Design ship log entry, and CT_WARP_TOWER_MAP_X4
        // is the 2nd. We swap X4 and X2 here on purpose to make the numbers in our location names match the ship log display order.
        { Location.SLF__CT_WARP_TOWER_MAP_X1, "ET Ship Log: AT Tower Designs 1 - Identify" },
        { Location.SLF__CT_WARP_TOWER_MAP_X4, "ET Ship Log: AT Tower Designs 2 - Different Planets" },
        { Location.SLF__CT_WARP_TOWER_MAP_X3, "ET Ship Log: AT Tower Designs 3 - Reflect Destinations" },
        { Location.SLF__CT_WARP_TOWER_MAP_X2, "ET Ship Log: AT Tower Designs 4 - ATP" },
        { Location.SLF__CT_SUNLESS_CITY_X1, "ET Ship Log: Sunless City 1 - Identify" },
        { Location.SLF__CT_SUNLESS_CITY_X2, "ET Ship Log: Sunless City 2 - Sun Station Debate" },
        { Location.SLF__CT_SUNLESS_CITY_X3, "ET Ship Log: Sunless City 3 - Signal" },
        { Location.SLF__CT_ANGLERFISH_FOSSIL_X1, "ET Ship Log: Anglerfish Fossil 1 - Children's Game" },
        { Location.SLF__CT_ANGLERFISH_FOSSIL_X2, "ET Ship Log: Anglerfish Fossil 2 - Blindfold Rule" },
        { Location.SLF__CT_ANGLERFISH_FOSSIL_X3, "ET Ship Log: Anglerfish Fossil 3 - Adult Response" },
        { Location.SLF__CT_QUANTUM_CAVES_X1, "ET Ship Log: Quantum Caves 1 - Wandering Rock" },
        { Location.SLF__CT_QUANTUM_CAVES_X2, "ET Ship Log: Quantum Caves 2 - Quantum Signal" },
        { Location.SLF__CT_LAKEBED_CAVERN_X1, "ET Ship Log: Lakebed Cave 1 - Coleus Disappeared" },
        { Location.SLF__CT_LAKEBED_CAVERN_X2, "ET Ship Log: Lakebed Cave 2 - Entanglement Rule" },
        { Location.SLF__CT_LAKEBED_CAVERN_X3, "ET Ship Log: Lakebed Cave 3 - Theorizing" },
        { Location.SLF__TT_WARP_TOWERS_X1, "AT Ship Log: Towers 1 - Identify" },
        { Location.SLF__TT_WARP_TOWERS_X2, "AT Ship Log: Towers 2 - WHS" },
        { Location.SLF__TT_TIME_LOOP_DEVICE_X1, "AT Ship Log: ATP 1 - Entered" },
        { Location.SLF__TT_TIME_LOOP_DEVICE_X2, "AT Ship Log: ATP 2 - Monoliths" },
        { Location.SLF__TT_TIME_LOOP_DEVICE_X3, "AT Ship Log: ATP 3 - Energy" },
        { Location.SLF__TT_TIME_LOOP_DEVICE_X4, "AT Ship Log: ATP 4 - Sun Station" },
        { Location.SLF__TT_TIME_LOOP_DEVICE_X5, "AT Ship Log: ATP 5 - Core" },
        { Location.SLF__TH_VILLAGE_X1, "TH Ship Log: Village 1 - Identify" },
        { Location.SLF__TH_VILLAGE_X2, "TH Ship Log: Village 2 - Statue Eyes Opened" },
        // Logsanity no longer generates the Village 3 location because it turns out this fact is perma-missable.
        // Keeping it here for backwards compatibility and to document that this is intentional.
        { Location.SLF__TH_VILLAGE_X3, "TH Ship Log: Village 3 - Never Opened Before" },
        { Location.SLF__TH_ZERO_G_CAVE_X1, "TH Ship Log: Zero-G Cave 1 - Identify" },
        { Location.SLF__TH_ZERO_G_CAVE_X2, "TH Ship Log: Zero-G Cave 2 - Repair" },
        { Location.SLF__TH_IMPACT_CRATER_X1, "TH Ship Log: Dark Bramble Seed 1 - Tektite" },
        { Location.SLF__TH_IMPACT_CRATER_X2, "TH Ship Log: Dark Bramble Seed 2 - Harmonica Signal" },
        { Location.SLF__TH_IMPACT_CRATER_X3, "TH Ship Log: Dark Bramble Seed 3 - Scout Photos" },
        { Location.SLF__TH_NOMAI_MINE_X1, "TH Ship Log: Nomai Mines 1 - Shell" },
        { Location.SLF__TH_NOMAI_MINE_X2, "TH Ship Log: Nomai Mines 2 - No Physical Entrance" },
        { Location.SLF__TH_NOMAI_MINE_X3, "TH Ship Log: Nomai Mines 3 - Four-Eyed Lifeforms" },
        { Location.SLF__TH_QUANTUM_SHARD_X1, "TH Ship Log: Quantum Grove 1 - Quantum Signal" },
        { Location.SLF__TH_QUANTUM_SHARD_X2, "TH Ship Log: Quantum Grove 2 - Poem" },
        { Location.SLF__TM_ESKER_X1, "AR Ship Log: Esker's Camp" },
        { Location.SLF__TM_NORTH_POLE_X1, "AR Ship Log: Lunar Lookout" },
        { Location.SLF__TM_EYE_LOCATOR_X1, "AR Ship Log: Eye Signal Locator 1 - Identify" },
        { Location.SLF__TM_EYE_LOCATOR_X2, "AR Ship Log: Eye Signal Locator 2 - Failure" },
        { Location.SLF__BH_RIEBECK_X1, "BH Ship Log: Riebeck's Camp 1 - Visit" },
        { Location.SLF__BH_RIEBECK_X2, "BH Ship Log: Riebeck's Camp 2 - Archaeology" },
        { Location.SLF__BH_GRAVITY_CANNON_X1, "BH Ship Log: Gravity Cannon 1 - Activate" },
        { Location.SLF__BH_GRAVITY_CANNON_X2, "BH Ship Log: Gravity Cannon 2 - Recall" },
        { Location.SLF__BH_QUANTUM_RESEARCH_TOWER_X1, "BH Ship Log: Tower 1 - Sixth Location" },
        { Location.SLF__BH_QUANTUM_RESEARCH_TOWER_X2, "BH Ship Log: Tower 2 - Pilgrimage" },
        { Location.SLF__BH_QUANTUM_RESEARCH_TOWER_X3, "BH Ship Log: Tower 3 - United Goal" },
        { Location.SLF__BH_QUANTUM_SHARD_X1, "BH Ship Log: Tower Shard 1 - Grove Objects" },
        { Location.SLF__BH_QUANTUM_SHARD_X2, "BH Ship Log: Tower Shard 2 - Hypothesis" },
        { Location.SLF__BH_QUANTUM_SHARD_X3, "BH Ship Log: Tower Shard 3 - QM Signal" },
        { Location.SLF__BH_WARP_RECEIVER_X1, "BH Ship Log: Northern Glacier 1 - Identify" },
        { Location.SLF__BH_WARP_RECEIVER_X2, "BH Ship Log: Northern Glacier 2 - WHS" },
        { Location.SLF__BH_ESCAPE_POD_X1, "BH Ship Log: Escape Pod 1 1 - Identify" },
        { Location.SLF__BH_ESCAPE_POD_X2, "BH Ship Log: Escape Pod 1 2 - Vessel" },
        { Location.SLF__BH_OLD_SETTLEMENT_X1, "BH Ship Log: Old Settlement 1 - Identify" },
        { Location.SLF__BH_OLD_SETTLEMENT_X2, "BH Ship Log: Old Settlement 2 - Eye-Shaped Signal" },
        { Location.SLF__BH_OLD_SETTLEMENT_X3, "BH Ship Log: Old Settlement 3 - Named" },
        { Location.SLF__BH_OLD_SETTLEMENT_X4, "BH Ship Log: Old Settlement 4 - Abandoned" },
        { Location.SLF__BH_MURAL_3_X1, "BH Ship Log: Old Settlement Mural 3" },
        { Location.SLF__BH_MURAL_2_X1, "BH Ship Log: Old Settlement Mural 2" },
        { Location.SLF__BH_MURAL_1_X1, "BH Ship Log: Old Settlement Mural 1" },
        { Location.SLF__BH_HANGING_CITY_X1, "BH Ship Log: Hanging City 1 - Visit" },
        { Location.SLF__BH_HANGING_CITY_X2, "BH Ship Log: Hanging City 2 - BHF Switch" },
        { Location.SLF__BH_HANGING_CITY_X3, "BH Ship Log: Hanging City 3 - Warp Core" },
        { Location.SLF__BH_HANGING_CITY_X4, "BH Ship Log: Hanging City 4 - Signal" },
        { Location.SLF__BH_BLACK_HOLE_FORGE_X1, "BH Ship Log: Black Hole Forge 1 - Astral Body Alignment" },
        { Location.SLF__BH_BLACK_HOLE_FORGE_X3, "BH Ship Log: Black Hole Forge 2 - Receiver Location" },
        { Location.SLF__BH_BLACK_HOLE_FORGE_X4, "BH Ship Log: Black Hole Forge 3 - Hourglass Twins" },
        { Location.SLF__BH_BLACK_HOLE_FORGE_X5, "BH Ship Log: Black Hole Forge 4 - Ash Twin Towers" },
        { Location.SLF__BH_BLACK_HOLE_FORGE_X6, "BH Ship Log: Black Hole Forge 5 - Poke's Warp Core" },
        { Location.SLF__BH_WARP_ALIGNMENT_MAP_X1, "BH Ship Log: Alignment Angle Diagram 1 - Identify" },
        { Location.SLF__BH_WARP_ALIGNMENT_MAP_X2, "BH Ship Log: Alignment Angle Diagram 2 - Five Degrees" },
        { Location.SLF__BH_WARP_ALIGNMENT_MAP_X3, "BH Ship Log: Alignment Angle Diagram 3 - Several Seconds" },
        { Location.SLF__BH_WARP_ALIGNMENT_MAP_X4, "BH Ship Log: Alignment Angle Diagram 4 - Active Window" },
        { Location.SLF__BH_OBSERVATORY_X1, "BH Ship Log: Southern Observatory 1 - Signal" },
        { Location.SLF__BH_OBSERVATORY_X2, "BH Ship Log: Southern Observatory 2 - Distant Orbit" },
        { Location.SLF__BH_OBSERVATORY_X3, "BH Ship Log: Southern Observatory 3 - Deep Space Probe" },
        { Location.SLF__BH_OBSERVATORY_X4, "BH Ship Log: Southern Observatory 4 - Probability" },
        { Location.SLF__BH_TORNADO_SIMULATION_X1, "BH Ship Log: Tornado Simulation 1 - Most Cyclones" },
        { Location.SLF__BH_TORNADO_SIMULATION_X2, "BH Ship Log: Tornado Simulation 2 - Below" },
        { Location.SLF__VM_VOLCANO_X1, "HL Ship Log: Volcanic Testing Site 1 - Purpose" },
        { Location.SLF__VM_VOLCANO_X2, "HL Ship Log: Volcanic Testing Site 2 - Shell" },
        { Location.SLF__VM_VOLCANO_X3, "HL Ship Log: Volcanic Testing Site 3 - Smallest Crack" },
        { Location.SLF__GD_OCEAN_X1, "GD Ship Log: Ocean Depths 1 - Electrical Field" },
        { Location.SLF__GD_OCEAN_X2, "GD Ship Log: Ocean Depths 2 - Coral Forest" },
        { Location.SLF__GD_GABBRO_ISLAND_X0, "GD Ship Log: Gabbro's Island 1 - Hammock" },
        { Location.SLF__GD_GABBRO_ISLAND_X1, "GD Ship Log: Gabbro's Island 2 - Gabbro's Statue" },
        { Location.SLF__GD_GABBRO_ISLAND_X2, "GD Ship Log: Gabbro's Island 3 - Remembers" },
        { Location.SLF__GD_GABBRO_ISLAND_X3, "GD Ship Log: Gabbro's Island 4 - Only Ones" },
        { Location.SLF__GD_CONSTRUCTION_YARD_X1, "GD Ship Log: Construction Yard 1 - Built OPC" },
        { Location.SLF__GD_CONSTRUCTION_YARD_X2, "GD Ship Log: Construction Yard 2 - Hiatus" },
        { Location.SLF__GD_CONSTRUCTION_YARD_X3, "GD Ship Log: Construction Yard 3 - Launch" },
        { Location.SLF__GD_BRAMBLE_ISLAND_X1, "GD Ship Log: Bramble Island" },
        { Location.SLF__GD_STATUE_ISLAND_X1, "GD Ship Log: Statue Island 1 - Purpose" },
        { Location.SLF__GD_STATUE_ISLAND_X2, "GD Ship Log: Statue Island 2 - Beach Statue" },
        { Location.SLF__GD_STATUE_WORKSHOP_X1, "GD Ship Log: Island Workshop 1 - Memories" },
        { Location.SLF__GD_STATUE_WORKSHOP_X2, "GD Ship Log: Island Workshop 2 - Masks" },
        { Location.SLF__GD_STATUE_WORKSHOP_X3, "GD Ship Log: Island Workshop 3 - Activation" },
        { Location.SLF__GD_QUANTUM_TOWER_X1, "GD Ship Log: Tower 1 - Journey" },
        { Location.SLF__GD_QUANTUM_TOWER_X2, "GD Ship Log: Tower 2 - Observing" },
        { Location.SLF__GD_QUANTUM_TOWER_X3, "GD Ship Log: Tower 3 - Rule of Imaging" },
        { Location.SLF__GD_QUANTUM_TOWER_X4, "GD Ship Log: Tower 4 - Other Shards" },
        { Location.SLF__ORBITAL_PROBE_CANNON_X1, "GD Ship Log: OPC 1 - Entered" },
        { Location.SLF__ORBITAL_PROBE_CANNON_X2, "GD Ship Log: OPC 2 - Purpose" },
        { Location.SLF__ORBITAL_PROBE_CANNON_X3, "GD Ship Log: OPC 3 - Maximum Power" },
        { Location.SLF__OPC_SUNKEN_MODULE_X1, "GD Ship Log: Probe Tracking Module 1 - Millions" },
        { Location.SLF__OPC_SUNKEN_MODULE_X2, "GD Ship Log: Probe Tracking Module 2 - Anomaly Located" },
        { Location.SLF__OPC_SUNKEN_MODULE_X3, "GD Ship Log: Probe Tracking Module 3 - Statue" },
        { Location.SLF__OPC_EYE_COORDINATES_X1, "GD Ship Log: Probe Tracking Module 4 - Coordinates" },
        { Location.SLF__OPC_BROKEN_MODULE_X1, "GD Ship Log: Launch Module 1 - Damaged" },
        { Location.SLF__OPC_BROKEN_MODULE_X2, "GD Ship Log: Launch Module 2 - Only Once" },
        { Location.SLF__OPC_BROKEN_MODULE_X3, "GD Ship Log: Launch Module 3 - Receive Data" },
        { Location.SLF__OPC_INTACT_MODULE_X1, "GD Ship Log: Control Module 1 - Request" },
        { Location.SLF__OPC_INTACT_MODULE_X2, "GD Ship Log: Control Module 2 - Status" },
        { Location.SLF__DB_FELDSPAR_X1, "DB Ship Log: Feldspar's Camp 1 - Status" },
        { Location.SLF__DB_FELDSPAR_X2, "DB Ship Log: Feldspar's Camp 2 - Space Doesn't Work" },
        { Location.SLF__DB_FELDSPAR_X3, "DB Ship Log: Feldspar's Camp 3 - Peace And Quiet" },
        { Location.SLF__DB_FROZEN_JELLYFISH_X1, "DB Ship Log: Frozen Jellyfish 1 - Outside" },
        { Location.SLF__DB_FROZEN_JELLYFISH_X2, "DB Ship Log: Frozen Jellyfish 2 - Inside" },
        { Location.SLF__DB_FROZEN_JELLYFISH_X3, "DB Ship Log: Frozen Jellyfish 3 - Do Not Eat" },
        { Location.SLF__DB_ESCAPE_POD_X1, "DB Ship Log: Escape Pod 3 1 - Identify" },
        { Location.SLF__DB_ESCAPE_POD_X2, "DB Ship Log: Escape Pod 3 2 - Vessel" },
        { Location.SLF__DB_ESCAPE_POD_X3, "DB Ship Log: Escape Pod 3 3 - Two Beacons" },
        { Location.SLF__DB_NOMAI_GRAVE_X1, "DB Ship Log: Nomai Grave 1 - Followed Beacon" },
        { Location.SLF__DB_NOMAI_GRAVE_X2, "DB Ship Log: Nomai Grave 2 - Within the Seed" },
        { Location.SLF__DB_NOMAI_GRAVE_X3, "DB Ship Log: Nomai Grave 3 - Beacon Dying" },
        { Location.SLF__DB_NOMAI_GRAVE_X4, "DB Ship Log: Nomai Grave 4 - Scout Photos" },
        { Location.SLF__DB_VESSEL_X1, "DB Ship Log: The Vessel 1 - Entered" },
        { Location.SLF__DB_VESSEL_X2, "DB Ship Log: The Vessel 2 - Dead Core" },
        { Location.SLF__DB_VESSEL_X3, "DB Ship Log: The Vessel 3 - Input Pillar" },
        { Location.SLF__DB_VESSEL_X4, "DB Ship Log: The Vessel 4 - Call For Help" },
        { Location.SLF__DB_VESSEL_X5, "DB Ship Log: The Vessel 5 - Clans Regrouping" },
        { Location.SLF__DB_VESSEL_X6, "DB Ship Log: The Vessel 6 - Original Recording" },
        { Location.SLF__WHS_X1, "Ship Log: WHS 1 - Warp Towers" },
        { Location.SLF__WHS_X2, "Ship Log: WHS 2 - Alignment" },
        { Location.SLF__WHS_X3, "Ship Log: WHS 3 - Temporal Anomaly" },
        { Location.SLF__WHS_X4, "Ship Log: WHS 4 - Miniscule Interval" },
        { Location.SLF__COMET_SHUTTLE_X1, "Ship Log: Frozen Shuttle 1 - Identify" },
        { Location.SLF__COMET_SHUTTLE_X2, "Ship Log: Frozen Shuttle 2 - Energy Readings" },
        { Location.SLF__COMET_SHUTTLE_X3, "Ship Log: Frozen Shuttle 3 - Stayed" },
        { Location.SLF__COMET_SHUTTLE_X4, "Ship Log: Frozen Shuttle 4 - Lost Contact" },
        { Location.SLF__COMET_INTERIOR_X1, "Ship Log: Ruptured Core 1 - Missing Crew" },
        { Location.SLF__COMET_INTERIOR_X2, "Ship Log: Ruptured Core 2 - Exotic Matter" },
        { Location.SLF__COMET_INTERIOR_X3, "Ship Log: Ruptured Core 3 - Instant Blanket" },
        { Location.SLF__COMET_INTERIOR_X4, "Ship Log: Ruptured Core 4 - Warn the Others" },
        { Location.SLF__QUANTUM_MOON_X1, "QM Ship Log: QM 1 - Land" },
        { Location.SLF__QUANTUM_MOON_X2, "QM Ship Log: QM 2 - Corpse" },
        { Location.SLF__QM_SHUTTLE_X1, "Ship Log: Solanum's Shuttle 1 - Landing" },
        { Location.SLF__QM_SHUTTLE_X2, "Ship Log: Solanum's Shuttle 2 - South Pole" },
        { Location.SLF__QM_SHRINE_X1, "QM Ship Log: Quantum Shrine 1 - Identify" },
        { Location.SLF__QM_SHRINE_X2, "QM Ship Log: Quantum Shrine 2 - Imaging Rule" },
        { Location.SLF__QM_SHRINE_X3, "QM Ship Log: Quantum Shrine 3 - Entanglement Rule" },
        { Location.SLF__QM_SHRINE_X4, "QM Ship Log: Quantum Shrine 4 - Sixth Location Rule" },
        { Location.SLF__QM_SIXTH_LOCATION_X1, "QM Ship Log: Sixth Location 1 - Visit" },
        { Location.SLF__QM_SIXTH_LOCATION_X3, "QM Ship Log: Sixth Location 2 - Moon" },
        { Location.SLF__QM_SIXTH_LOCATION_X5, "QM Ship Log: Sixth Location 3 - Reflection" },
        { Location.SLF__QM_SIXTH_LOCATION_X4, "QM Ship Log: Sixth Location 4 - Source" },
        { Location.SLF__QM_SIXTH_LOCATION_X2, "QM Ship Log: Sixth Location 5 - Conscious Observer" },
        { Location.SLF__QM_SIXTH_LOCATION_X6, "QM Ship Log: Sixth Location 6 - Status" },

        // DLC & Logsanity Locations
        { Location.SLF__TH_RADIO_TOWER_X1, "TH Ship Log: Radio Tower" },
        { Location.SLF__IP_RING_WORLD_X1, "EotE Ship Log: The Stranger" },

        { Location.SLF__IP_ZONE_1_X1, "EotE Ship Log: River Lowlands 1 - Visit" },
        { Location.SLF__IP_ZONE_1_X2, "EotE Ship Log: River Lowlands 2 - Workshop" },
        { Location.SLF__IP_ZONE_1_STORY_X1, "EotE Ship Log: Lowlands Slide Reel 1 - Origin" },
        { Location.SLF__IP_ZONE_1_STORY_X2, "EotE Ship Log: Lowlands Slide Reel 2 - Burned" },
        { Location.SLF__IP_ZONE_2_X1, "EotE Ship Log: Cinder Isles 1 - Visit" },
        { Location.SLF__IP_ZONE_2_X2, "EotE Ship Log: Cinder Isles 2 - Eye" },
        { Location.SLF__IP_ZONE_2_STORY_X1, "EotE Ship Log: Cinder Isles Slide Reel 1 - Anomaly" },
        { Location.SLF__IP_ZONE_2_STORY_X2, "EotE Ship Log: Cinder Isles Slide Reel 2 - Burned" },
        { Location.SLF__IP_ZONE_2_LIGHTHOUSE_X2, "EotE Ship Log: Island Tower 1 - Upper Floors" },
        { Location.SLF__IP_ZONE_2_LIGHTHOUSE_X1, "EotE Ship Log: Island Tower 2 - Slide Reel" },
        { Location.SLF__IP_ZONE_3_X1, "EotE Ship Log: Hidden Gorge 1 - Visit" },
        { Location.SLF__IP_ZONE_3_STORY_X1, "EotE Ship Log: Hidden Gorge Slide Reel 1 - Green Fire" },
        { Location.SLF__IP_ZONE_3_STORY_X2, "EotE Ship Log: Hidden Gorge Slide Reel 2 - Burned" },
        // for some reason the _LAB_ facts are about Abandoned Temple, while the _ENTRANCE_ facts are about the Lab
        { Location.SLF__IP_ZONE_3_ENTRANCE_X1, "EotE Ship Log: Laboratory 1 - Enter" },
        { Location.SLF__IP_ZONE_3_ENTRANCE_X2, "EotE Ship Log: Laboratory 2 - Sleep" },
        { Location.SLF__IP_ZONE_3_ENTRANCE_X3, "EotE Ship Log: Laboratory 3 - Experiments" },
        { Location.SLF__IP_ZONE_4_X2, "EotE Ship Log: Reservoir 1 - Visit" },
        { Location.SLF__IP_ZONE_4_X3, "EotE Ship Log: Reservoir 2 - Broken Connection" },
        { Location.SLF__IP_ZONE_4_X4, "EotE Ship Log: Reservoir 3 - Predicted Radius" },
        { Location.SLF__IP_ZONE_4_STORY_X1, "EotE Ship Log: Reservoir Slide Reel 1 - Vault" },
        { Location.SLF__IP_ZONE_4_STORY_X2, "EotE Ship Log: Reservoir Slide Reel 2 - Burned" },
        { Location.SLF__IP_PRISON_X1, "EotE Ship Log: Submerged Structure 1 - Enter" },
        { Location.SLF__IP_PRISON_X2, "EotE Ship Log: Submerged Structure 2 - Vault" },

        { Location.SLF__IP_DREAM_ZONE_1_X1, "DW Ship Log: Shrouded Woodlands 1 - Visit" },
        { Location.SLF__IP_DREAM_ZONE_1_X2, "DW Ship Log: Shrouded Woodlands 2 - Music" },
        { Location.SLF__IP_DREAM_ZONE_1_X3, "DW Ship Log: Shrouded Woodlands 3 - Covered Bridge" },
        { Location.SLF__IP_DREAM_ZONE_2_X1, "DW Ship Log: Starlit Cove 1 - Visit" },
        { Location.SLF__IP_DREAM_ZONE_2_X2, "DW Ship Log: Starlit Cove 2 - Alarm Bell" },
        { Location.SLF__IP_DREAM_ZONE_2_X3, "DW Ship Log: Starlit Cove 3 - Burned Building" },
        { Location.SLF__IP_DREAM_ZONE_2_X4, "DW Ship Log: Starlit Cove 4 - Upper Floors" },
        { Location.SLF__IP_DREAM_ZONE_3_X1, "DW Ship Log: Endless Canyon 1 - Visit" },
        { Location.SLF__IP_DREAM_ZONE_3_X2, "DW Ship Log: Endless Canyon 2 - Mural" },
        { Location.SLF__IP_DREAM_LAKE_X1, "DW Ship Log: Subterranean Lake 1 - Visit" },
        { Location.SLF__IP_DREAM_LAKE_X2, "DW Ship Log: Subterranean Lake 2 - Green Light" },

        { Location.SLF__IP_ZONE_2_CODE_X1, "EotE Ship Log: Symbol Room 1 - Enter" },
        { Location.SLF__IP_ZONE_2_CODE_X2, "EotE Ship Log: Symbol Room 2 - Burned Away" },
        { Location.SLF__IP_ZONE_2_CODE_X3, "EotE Ship Log: Symbol Room 3 - Reel Symbol" },
        { Location.SLF__IP_ZONE_3_LAB_X1, "EotE Ship Log: Abandoned Temple 1 - Enter" },
        { Location.SLF__IP_ZONE_3_LAB_X3, "EotE Ship Log: Abandoned Temple 2 - Symbols" },
        { Location.SLF__IP_ZONE_3_LAB_X4, "EotE Ship Log: Abandoned Temple 3 - Secret Room" },
        { Location.SLF__IP_ZONE_3_LAB_X2, "EotE Ship Log: Abandoned Temple 4 - Reels" },
        { Location.SLF__IP_MAP_PROJECTION_1_X1, "EotE Ship Log: Map Projection 1" },
        { Location.SLF__IP_MAP_PROJECTION_2_X1, "EotE Ship Log: Map Projection 2" },
        { Location.SLF__IP_MAP_PROJECTION_3_X1, "EotE Ship Log: Map Projection 3" },

        { Location.SLF__IP_ZONE_1_SECRET_X2, "EotE Ship Log: River Lowlands Secret Room 1 - Enter" },
        { Location.SLF__IP_ZONE_1_SECRET_X1, "EotE Ship Log: River Lowlands Secret Room 2 - Slide Reel" },
        { Location.SLF__IP_ZONE_2_SECRET_X2, "EotE Ship Log: Cinder Isles Secret Room 1 - Enter" },
        { Location.SLF__IP_ZONE_2_SECRET_X1, "EotE Ship Log: Cinder Isles Secret Room 2 - Slide Reel" },
        { Location.SLF__IP_ZONE_3_SECRET_X2, "EotE Ship Log: Hidden Gorge Secret Room 1 - Enter" },
        { Location.SLF__IP_ZONE_3_SECRET_X1, "EotE Ship Log: Hidden Gorge Secret Room 2 - Slide Reel" },

        { Location.SLF__IP_DREAM_LIBRARY_1_X1, "DW Ship Log: Shrouded Woodlands Archive 1 - Enter" },
        { Location.SLF__IP_DREAM_LIBRARY_1_X2, "DW Ship Log: Shrouded Woodlands Archive 2 - Destroyed" },
        { Location.SLF__IP_DREAM_1_STORY_X1, "DW Ship Log: Shrouded Woodlands Archive 3 - Origin" },
        { Location.SLF__IP_DREAM_1_STORY_X2, "DW Ship Log: Shrouded Woodlands Archive 4 - Sacrifice" },
        { Location.SLF__IP_DREAM_1_RULE_X1, "DW Ship Log: Shrouded Woodlands Archive 5 - Jumping Off" },
        { Location.SLF__IP_DREAM_LIBRARY_2_X1, "DW Ship Log: Starlit Cove Archive 1 - Enter" },
        { Location.SLF__IP_DREAM_LIBRARY_2_X2, "DW Ship Log: Starlit Cove Archive 2 - Destroyed" },
        { Location.SLF__IP_DREAM_2_STORY_X1, "DW Ship Log: Starlit Cove Archive 3 - Anomaly" },
        { Location.SLF__IP_DREAM_2_STORY_X2, "DW Ship Log: Starlit Cove Archive 4 - Signal Blocker" },
        { Location.SLF__IP_DREAM_2_RULE_X1, "DW Ship Log: Starlit Cove Archive 5 - After Death" },
        { Location.SLF__IP_DREAM_2_RULE_X2, "DW Ship Log: Starlit Cove Archive 6 - Failing Bell" },
        { Location.SLF__IP_DREAM_LIBRARY_3_X1, "DW Ship Log: Endless Canyon Archive 1 - Enter" },
        { Location.SLF__IP_DREAM_LIBRARY_3_X2, "DW Ship Log: Endless Canyon Archive 2 - Destroyed" },
        { Location.SLF__IP_DREAM_3_STORY_X1, "DW Ship Log: Endless Canyon Archive 3 - Green Fire" },
        { Location.SLF__IP_DREAM_3_STORY_X2, "DW Ship Log: Endless Canyon Archive 4 - Simulated" },
        { Location.SLF__IP_DREAM_3_RULE_X1, "DW Ship Log: Endless Canyon Archive 5 - Walking Beyond" },

        { Location.SLF__IP_SARCOPHAGUS_X2, "DW Ship Log: Sealed Vault 1 - Imprisoned" },
        { Location.SLF__IP_SARCOPHAGUS_X3, "DW Ship Log: Sealed Vault 2 - Actions" },
        { Location.SLF__IP_SARCOPHAGUS_X4, "DW Ship Log: Sealed Vault 3 - History" },
        { Location.SLF__IP_SARCOPHAGUS_X5, "DW Ship Log: Sealed Vault 4 - Farewell" },
    };

    public static Dictionary<string, Location> locationNamesReversed = locationNames.ToDictionary(ln => ln.Value, ln => ln.Key);

    public static string LocationToName(Location location) => locationNames[location];
    public static Location NameToLocation(string locationName) => locationNamesReversed[locationName];

    public static Dictionary<string, Location> frequencyToLocation = new Dictionary<string, Location>{
        { "EscapePod", Location.FREQ_DISTRESS },
        { "Quantum", Location.FREQ_QUANTUM },
        { "HideAndSeek", Location.FREQ_HIDE_SEEK },
        // left out Default, WarpCore and Statue because I don't believe they get used, and Radio because I don't think we need another "scan any..." location
    };
    public static Dictionary<Location, string> locationToFrequency = frequencyToLocation.ToDictionary(ftl => ftl.Value, ftl => ftl.Key);

    public static Dictionary<string, Location> signalToLocation = new Dictionary<string, Location>{
        { "Traveler_Chert", Location.ET_DRUM },
        { "Traveler_Esker", Location.AR_WHISTLE },
        { "Traveler_Riebeck", Location.BH_BANJO },
        { "Traveler_Gabbro", Location.GD_FLUTE },
        { "Traveler_Feldspar", Location.DB_HARMONICA },
        { "Quantum_TH_MuseumShard", Location.TH_MS_SIGNAL },
        { "Quantum_TH_GroveShard", Location.TH_GS_SIGNAL },
        { "Quantum_CT_Shard", Location.ET_SHARD_SIGNAL },
        { "Quantum_BH_Shard", Location.BH_SHARD_SIGNAL },
        { "Quantum_GD_Shard", Location.GD_SHARD_SIGNAL },
        { "Quantum_QM", Location.QM_SIGNAL },
        { "EscapePod_BH", Location.BH_EP1_SIGNAL },
        { "EscapePod_CT", Location.ET_EP2_SIGNAL },
        { "EscapePod_DB", Location.DB_EP3_SIGNAL },
        { "HideAndSeek_Galena", Location.TH_GALENA_SIGNAL },
        { "HideAndSeek_Tephra", Location.TH_TEPHRA_SIGNAL },
        { "RadioTower", Location.DSR_TOWER_SIGNAL },
        { "MapSatellite", Location.DSR_SATELLITE_SIGNAL },
        // left out Default, HideAndSeek_Arkose and all the White Hole signals because I don't believe they're used
        // left out Nomai and Prisoner because I believe those are only available during the finale
    };
    public static Dictionary<Location, string> locationToSignal = signalToLocation.ToDictionary(stl => stl.Value, stl => stl.Key);

    // leave these as null until we load the ids, so any attempt to work with ids before that will fail loudly
    public static Dictionary<long, Location> archipelagoIdToLocation = null;
    public static Dictionary<Location, long> locationToArchipelagoId = null;

    public static void LoadArchipelagoIds(string locationsFilepath)
    {
        var locationsData = JArray.Parse(File.ReadAllText(locationsFilepath));
        archipelagoIdToLocation = new();
        locationToArchipelagoId = new();
        foreach (var locationData in locationsData)
        {
            // Skip event locations, since they intentionally don't have ids
            if (locationData["address"].Type == JTokenType.Null) continue;

            var archipelagoId = (long)locationData["address"];
            var name = (string)locationData["name"];

            if (!locationNamesReversed.ContainsKey(name))
                throw new System.Exception($"LoadArchipelagoIds failed: unknown location name {name}");

            var location = locationNamesReversed[name];
            archipelagoIdToLocation.Add(archipelagoId, location);
            locationToArchipelagoId.Add(location, archipelagoId);
        }
    }
};
